me:
  name: Eleanor Clifford
  name_regex: (Ms )?Eleanor Clifford

people:
  - id: daniel-zeichner-mp
    name: Daniel Zeichner MP
    name_regex: (Mr )?Daniel Zeichner( MP)?
    emails:
      - daniel.zeichner.mp@parliament.uk
      - daniel@danielzeichner.co.uk

  - id: beccy-cooper-mp
    name: Dr Beccy Cooper MP
    name_regex: (Dr )?Beccy Cooper( MP)?
    emails:
      - beccy.cooper.mp@parliament.uk
      - casework@drbeccycooper.co.uk

  - id: joe-powell-mp
    name: Joe Powell MP
    name_regex: (Mr )?Joe Powell( MP)?
    emails:
      - joe.powell.mp@parliament.uk

  - id: lord-mark-pack
    name: Lord Mark Pack
    name_regex: (Lord |Dr\.? )?Mark( Pack)?
    emails:
      - mark.pack@gmail.com
      - fake-mark-pack@clifford.lol

  - id: ukri
    name: UK Research and Innovation
    name_regex: null
    emails:
      - talent@ukri.org

  - id: cfae
    name: Imperial College Centre for Academic English (CfAE)
    name_regex: null
    emails:
      - fake-cfae@clifford.lol

rules:
  days_assume_related: 14  # within which assume emails with different subjects are related
  subject_filters:
    '\(case ref: \w*\)$': ''
    'automat(ed|ic) reply:': ''
    '^re: *': ''
    'New submission from President form on website': ''
  ignore_messages_with_patterns:
    - 'automat(ed|ic) reply:'
    - '^Thank you$'
  dont_subject_combine:
    - "thank you for your email"

manual:
  - ts: 2025-06-30T22:44
    date: Wed, 30 Jun 2025 22:44:10 +0100
    to: Equality and Human Rights Commission
    subject: Response to EHRC consultation on updates to services Code of Practice
    href: ehrc-consultation.html

related:
  - - okiiclswbfv3xgedmbrm3mv4oiby7kmbv75wrr2hixnk52niuf@itret26teu7g
    - l75xGoxMRteDWvKvdn5I5Q@geopod-ismtpd-13

overrides:
  ii36ljh4bmj4kgnavlvqwy7nustq5hazxdamsdzz3l3nummelo@dwnhdzamyff6:
    markdown: true
    format:
      letter:
        filters:
          plain_body:
            '^(Many Thanks,)$': '\1<br>'

  kk5c2mf57kfcaxxrs4lkd6dpmidsufbewmnlchu4s2ri3qnqxp@cfsaxgnw2a5d:
    format:
      letter:
        filters:
          plain_body:
            "https://wss.pollfish.com/link/[0-9a-f-]*": "[redacted link]"
            '<a href="\[redacted link\]">([^<>]*)</a>': '\1'

  rnu5khsogbfzl4zxm7rhgdogjjemkbiz6prtb4q2lubwsr24vs@3jkyrk6w2rer:
    notes: |
      NB: brevity was due to 2000 character limit in web form
    index_subject: On the Data Bill "sex" and "acquired gender" amendment

  lppsxmjdl2e6ngtl6c363eu3qqsaa4ncp5xhvgkioobd3ydvhn@pqvrxbve3hix:
    notes: |
      NB: I can't recommend you write like this to your MP, they will just ignore you. But I was angry.

  CAKGS-Z-=W5iZxgGLeSGiSwYBY81LroU0xbCZc-9JZTz7sy4M5A@mail.gmail.com:
    format:
      letter:
        filters:
          html_body:
            "(?<!<br>)<br>(?!<br>)": "<br><br>"

  njv3bfwwgejogoimuouramof7obzfgqyvmcptkaj54jn6omvii@7cvicg7bv27i:
    notes: |
      NB: Based on <a href="https://action.goodlawproject.org/decriminalise-abortion">The Good Law Project's template</a>

  l75xGoxMRteDWvKvdn5I5Q@geopod-ismtpd-13:
    format:
      letter:
        filters:
          html_body:
            '(<em>Joe</em>).*': '\1'

format:
  index:
    outer: |
      ---
      color: purple
      ---

      This is an archive of political or otherwise important letters, emails,
      and similar that I have written, including to Members of Parliament
      (MPs), other politicians, and institutions, and including their responses
      where appropriate. You are free to use any of my works here as a starting
      point for your own letters. Please _do not_ credit me without asking me
      first.

      [If you live in the UK, you can find the contact details of your MP
      here.](https://members.parliament.uk/FindYourMP)

      _Please note: I have published the responses to my letters only when the
      author is responding in their capacity as a public official, as it is
      overwhelmingly in the public interest. However, please remember that such
      authors retain the legal rights to their work._

      ```{=html}
      <style>${CSS}</style>
      <div class="emails">
      <hr>
      ${CONTENT}
      <hr>
      </div>
      ```
    item: |
      <a href="${href}">
        <div class="email-item">
          <div class="email-header">
            <div class="email-to">${To}</div>
            <div class="email-date">${Date}</div>
          </div>
          <div class="email-subject">${Subject}</div>
        </div>
      </a>

    separator: <hr>

    css: |
      .page { max-width: 600px !important; margin: auto !important; }
      .emails a { color: #f8f8f2 !important; }
      .emails a:hover { color: #bd93f9 !important; }

      .email-item { margin: 20px 0px; }
      .email-header { display: flex; }
      .email-date { margin-left: auto }
      .email-subject { font-weight: 200; font-size: 1.3em; margin-left: 20px; }

  letter:
    outer: |
      ---
      color: purple
      ---

      ```{=html}
      <style>${CSS}</style>
      <div class="letters-return">
        <h2><a href="/documents/letters/">↩︎ Other letters</a></h2>
      </div>
      ${CONTENT}
      ```

    item: |
      ${NOTE}
      <p style="white-space: pre-wrap;">Date: ${Date}
      From: ${From}
      To: ${To}${MaybeSubject}${Body}

    note: |
      <p><em>${CONTENT}</em></p>

    separator: <hr>

    css: |
      .letters-return { margin: 20px 0px; }

    plain_body: |


      ${CONTENT}</p>

    md_body: |
      </p>
      ${CONTENT}

    html_body: |
      </p><p>
      ${CONTENT}
      </p>

    filters:
      plain_body:
        '^-- ?\n.*': ''
        '\n> ?(.*?)\n\n?': '</p><blockquote><p style="white-space: pre-wrap;">\1</p></blockquote><p style="white-space: pre-wrap;">'
        '(?:^$\n)?^(${name})$.*': '\1'
        '(https?:\/\/[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*))(?<![])])': '<a href="\1">\1</a>'  # https://stackoverflow.com/a/3809435


      html_body:
        '_________.*': ''
        '<([^<>]*)style="[^"]*"': '<\1'
        "<([^<>]*)style='[^']*'": '<\1'
        #'<div class="signature-container">([^<]*).*': '\1'
        '</?(div|img)[^>]*>': ''
        '&nbsp;(?=$|<br)': ''
        '^&nbsp;': ''
        '(^|<br>)(?:<[^>]*>)*(${name})(?:<[^>]*>)*(?:$|<br>).*': '\1\2'
