me:
  name: Eleanor Clifford
  name_regex: (Ms )?Eleanor Clifford

people:
  - id: daniel-zeichner-mp
    name: Daniel Zeichner MP
    name_regex: (Mr )?Daniel Zeichner( MP)?
    emails:
      - daniel.zeichner.mp@parliament.uk
      - daniel@danielzeichner.co.uk

  - id: beccy-cooper-mp
    name: Dr Beccy Cooper MP
    name_regex: (Dr )?Beccy Cooper( MP)?
    emails:
      - beccy.cooper.mp@parliament.uk
      - casework@drbeccycooper.co.uk

  - id: joe-powell-mp
    name: Joe Powell MP
    name_regex: (Mr )?Joe Powell( MP)?
    emails:
      - joe.powell.mp@parliament.uk

  - id: lord-mark-pack
    name: Lord Mark Pack
    name_regex: (Lord |Dr\.? )?Mark Pack
    emails:
      - mark.pack@gmail.com
      - fake-mark-pack@clifford.lol


rules:
  days_assume_related: 2  # within which assume emails with different subjects are related
  subject_filters:
    '\(case ref: \w*\)$': ''
    'automat(ed|ic) reply:': ''
    '^re: *': ''
  ignore_messages_with_patterns:
    - 'automat(ed|ic) reply:'
    - '^Thank you$'
  dont_subject_combine:
    - "thank you for your email"

format:
  between: <hr>

  format: |
    ${NOTE}
    <p style="white-space: pre-wrap;">Date: ${Date}
    From: ${From}
    To: ${To}${MaybeSubject}${Body}

  note: |
    <p><em>${CONTENT}</em></p>

  plain_body: |


    ${CONTENT}</p>

  html_body: |
    </p><p>
    ${CONTENT}
    </p>

  filters:
    plain_body:
      '^-- ?\n.*': ''
      '\n> ?(.*?)\n\n?': '</p><blockquote><p style="white-space: pre-wrap;">\1</p></blockquote><p style="white-space: pre-wrap;">'
      '(?:^$\n)?^(${name})$.*': '\1'

    html_body:
      '_________.*': ''
      '<([^<>]*)style="[^"]*"': '<\1'
      "<([^<>]*)style='[^']*'": '<\1'
      #'<div class="signature-container">([^<]*).*': '\1'
      '</?div[^>]*>': ''
      '&nbsp;$': ''
      '^&nbsp;': ''
      '^(?:<[^>]*>)*(${name})(?:<[^>]*>)*$.*': '\1'


notes:
  rnu5khsogbfzl4zxm7rhgdogjjemkbiz6prtb4q2lubwsr24vs@3jkyrk6w2rer: |
    NB: brevity is due to 2000 character limit in web form
