me:
  name: Eleanor Clifford
  name_regex: (Ms )?Eleanor Clifford

people:
  - id: daniel-zeichner-mp
    name: Daniel Zeichner MP
    name_regex: (Mr )?Daniel Zeichner( MP)?
    emails:
      - daniel.zeichner.mp@parliament.uk
      - daniel@danielzeichner.co.uk

  - id: beccy-cooper-mp
    name: Dr Beccy Cooper MP
    name_regex: (Dr )?Beccy Cooper( MP)?
    emails:
      - beccy.cooper.mp@parliament.uk
      - casework@drbeccycooper.co.uk

  #- id: joe-powell-mp
    #name: Joe Powell MP
    #name_regex: (Mr )?Joe Powell( MP)?
    #emails:
      #- joe.powell.mp@parliament.uk

  - id: lord-mark-pack
    name: Lord Mark Pack
    name_regex: (Lord |Dr\.? )?Mark( Pack)?
    emails:
      - mark.pack@gmail.com
      - fake-mark-pack@clifford.lol


rules:
  days_assume_related: 14  # within which assume emails with different subjects are related
  subject_filters:
    '\(case ref: \w*\)$': ''
    'automat(ed|ic) reply:': ''
    '^re: *': ''
    'New submission from President form on website': ''
  ignore_messages_with_patterns:
    - 'automat(ed|ic) reply:'
    - '^Thank you$'
  dont_subject_combine:
    - "thank you for your email"

format:
  separator: <hr>

  index:
    outer: |
      This is an archive of every letter/email I have written to politicians
      and the responses to them. You are free to use any of my works as a
      starting point for your own letters, without attribution.

      [If you live in the UK, you can find the contact details of your MP here.](https://members.parliament.uk/FindYourMP)

      _Please note: although I have published the responses to my letters as a
      matter of public interest, the authors retain all copyright rights over
      them._

      ```{=html}
      <div class="emails">
      <hr>
      ${CONTENT}
      <hr>
      </div>
      ```
    css: |
      .page { max-width: 600px !important; margin: auto !important; }
      .emails a { color: #f8f8f2 !important; }
      .emails a:hover { color: #bd93f9 !important; }

      .email-item { margin: 20px 0px; }
      .email-header { display: flex; }
      .email-date { margin-left: auto }
      .email-subject { font-weight: 200; font-size: 1.3em; margin-left: 20px; }

    format: |
      <a href="${href}">
        <div class="email-item">
          <div class="email-header">
            <div class="email-to">${To}</div>
            <div class="email-date">${Date}</div>
          </div>
          <div class="email-subject">${Subject}</div>
        </div>
      </a>

    separator: <hr>

  format: |
    ${NOTE}
    <p style="white-space: pre-wrap;">Date: ${Date}
    From: ${From}
    To: ${To}${MaybeSubject}${Body}

  note: |
    <p><em>${CONTENT}</em></p>

  plain_body: |


    ${CONTENT}</p>

  html_body: |
    </p><p>
    ${CONTENT}
    </p>

  filters:
    plain_body:
      '^-- ?\n.*': ''
      '\n> ?(.*?)\n\n?': '</p><blockquote><p style="white-space: pre-wrap;">\1</p></blockquote><p style="white-space: pre-wrap;">'
      '(?:^$\n)?^(${name})$.*': '\1'
      '(https?:\/\/[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*))(?<![])])': '<a href="\1">\1</a>'  # https://stackoverflow.com/a/3809435


    html_body:
      '_________.*': ''
      '<([^<>]*)style="[^"]*"': '<\1'
      "<([^<>]*)style='[^']*'": '<\1'
      #'<div class="signature-container">([^<]*).*': '\1'
      '</?div[^>]*>': ''
      '&nbsp;$': ''
      '^&nbsp;': ''
      '(^|<br>)(?:<[^>]*>)*(${name})(?:<[^>]*>)*(?:$|<br>).*': '\1\2'

overrides:
  rnu5khsogbfzl4zxm7rhgdogjjemkbiz6prtb4q2lubwsr24vs@3jkyrk6w2rer:
    notes: |
      NB: brevity was due to 2000 character limit in web form
    index_subject: On the Data Bill "sex" and "acquired gender" amendment

  lppsxmjdl2e6ngtl6c363eu3qqsaa4ncp5xhvgkioobd3ydvhn@pqvrxbve3hix:
    notes: |
      NB: I can't recommend you write like this to your MP, they will just ignore you. But I was angry.

  CAKGS-Z-=W5iZxgGLeSGiSwYBY81LroU0xbCZc-9JZTz7sy4M5A@mail.gmail.com:
    format:
      filters:
        html_body:
          "(?<!<br>)<br>(?!<br>)": "<br><br>"

  njv3bfwwgejogoimuouramof7obzfgqyvmcptkaj54jn6omvii@7cvicg7bv27i:
    notes: |
      NB: Based on <a href="https://action.goodlawproject.org/decriminalise-abortion">The Good Law Project's template</a>
